config/routes.rb
Rails.application.routes.draw do
  
  resources :trips do
    resources :status_times
 end
  
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  root 'pages#home' 
  
  devise_for :users
  
  


end

app/models/status_time.rb
class StatusTime < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
  #belongs_to :trip, :class_name => "Trip", :foreign_key => "trip_id"
  validates_presence_of :status 
  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :status_times
  accepts_nested_attributes_for :status_times
  validates_associated :status_times
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
         has_many :status_times
         has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/status_times_controller.rb
class StatusTimesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status_time, only: [:show, :edit, :update, :destroy]


#-------------------------------------------------------------------------------

  def index
    @status_times = current_user.status_times
    @status_time = StatusTime.new
    @user = current_user
  end

#-------------------------------------------------------------------------------

  def show
  end

#-------------------------------------------------------------------------------
 
  def new
    @status_time = StatusTime.new
  end

#-------------------------------------------------------------------------------

  def edit
  end

#-------------------------------------------------------------------------------

  def create
    # @status_time.trip_id = StatusTime.find(trip_id.last)
     @trip = Trip.find(params[:trip_id])
     
     @status_time = @trip.status_times.create(status_time_params)
     @status_time.user_id = current_user.id if current_user

      if @status_time.save
         redirect_to trip_path( @trip ), notice: 'Status time was successfully created.' 
    
      else
         render :new 
      
      end
    end
 

#-------------------------------------------------------------------------------
 
  def update
    respond_to do |format|
      if @status_time.update(status_time_params)
        format.html { redirect_to @status_time, notice: 'Status time was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_time }
      else
        format.html { render :edit }
        format.json { render json: @status_time.errors, status: :unprocessable_entity }
      end
    end
  end

#-------------------------------------------------------------------------------

  def destroy
    @status_time.destroy
    respond_to do |format|
      format.html { redirect_to status_times_url, notice: 'Status time was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#-------------------------------------------------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_time
      @status_time = StatusTime.find(params[:id])
    end

#-------------------------------------------------------------------------------
 
    def status_time_params
      params.require(:status_time).permit(
      :status, 
      :notes, 
      :trip_id, 
      :user_id,
      :location 
      )
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

#-------------------------------------------------------------------------------

  def index 
    @trips = current_user.trips
    @user = current_user
  end
  
#-------------------------------------------------------------------------------


  def show
  end
  
#-------------------------------------------------------------------------------  


  def new
    @trip = Trip.new
  end
  
  
#-------------------------------------------------------------------------------



  def edit
  end
  
#-------------------------------------------------------------------------------

  def create
   # @trip.status_times.user_id = current_user
   
    @trip = Trip.new(trip_params) 
    @trip.user_id = current_user.id if current_user
    


      if @trip.save
         redirect_to @trip, notice: 'Trip was successfully created.' 
 
      else
         render :new 
 
      
    end
  end
  
#-------------------------------------------------------------------------------

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end
  
#-------------------------------------------------------------------------------

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
#-------------------------------------------------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end
    
#-------------------------------------------------------------------------------

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(
        :user_id, 
        status_times_attributes: [
          :status_time_id, 
          :user_id, 
          :_destroy,
          :status,
          :notes,
          :location,
          :created_at,
          :updated_at,
          :trip_id,
          :id
          ]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
        # Returns the full title on a per-page basis.
    def full_title(page_title = '')
     base_title = "Fr8Quote Data"
    if page_title.empty?
     base_title 
    else
      page_title + " | " + base_title
    end
  end 
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/status_times_helper.rb
module StatusTimesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://www.chezzyk.com/">Chesnowitz Media is a division of Chezzy K Inc.</a>
<a>Riding the Rails in Canada</a></a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a>More stuff can go here</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "Chesnowitz Media", root_path, id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    
    
      <% if current_user %>
      <li></li>
      <li><%= link_to "Trips", trips_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    </ul>
    </nav>
    </div>
    </header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
    <!DOCTYPE html>
    <html>
    <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
    </head>
    <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <%= render 'layouts/messages' %>
    <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
    </body>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>All About Us</h1>
<p>The story of how we work and why we are the best!</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contacts</h1>
<p>A list of contact info</p>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1>Welcome To Chesnowitz Media!</h1>
<h2>

<a href="#">Chezzie's Awsome Apps!</a>

</h2>
<%= link_to "Sign up!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.ico"),
'http://chezzyk.com/' %>

app/views/shared/_index.html.erb
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
      <th>Status</th>
      <th>Service Time</th>
      <th>Notes</th>
      <th>Location</th>
      <th>User ID</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_times.each do |status_time| %>
      <tr>
        <td><%= status_time.status %></td>
        <td><%= status_time.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %></td>
        <td><%= status_time.notes %></td>
        <td><%= status_time.location %></td>
        
        <td><%= status_time.user_id %></td>
        <td><%= link_to 'Show', status_time, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_status_time_path(status_time), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', status_time, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
    </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<!--#<%= link_to 'New Status time', new_status_time_path %>-->

app/views/status_times/_form.html.erb
<%= simple_form_for(@status_time) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :status, collection: [ "On Duty Not Driving", "Driving", 
                    "Off Duty", "In Sleeper"], prompt: "Select Status"  %>
    <%= f.input :notes %>
    <%= f.input :location %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-mini btn-success' %>
  </div>
<% end %>

app/views/status_times/edit.html.erb
<h1>Editing Status Time</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_time %> |
<%= link_to 'Back', status_times_path %>

app/views/status_times/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Status Times</h1>
<%= render 'form' %>

<%= render 'shared/index' %>

app/views/status_times/new.html.erb
<h1>New Status Time</h1>

<%= render 'form' %>

<%= link_to 'Back', status_times_path %>

app/views/status_times/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driving Status:</strong>
  <%= @status_time.status %>
</p>

<p>
  <strong>Status Time:</strong>
  <%= @status_time.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %>
</p>


<p>
  <strong>Notes:</strong>
  <%= @status_time.notes %>
</p>

<p>
  <strong>Location:</strong>
  <%= @status_time.location %>
</p>

<p>
  <strong>Status record:</strong>
  <%=  %>
</p>

<%= link_to 'Edit', edit_status_time_path(@status_time) %> |
<%= link_to 'Back', status_times_path %>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
<%= f.error_notification %>
  <%= simple_fields_for :status_times do |s| %>

  <div class="form-inputs">
     <%= f.input :user_id,  class: :readonly %> 
     <%= s.input :status, collection: [ "On Duty Not Driving", "Driving", 
                    "Off Duty", "In Sleeper"], prompt: "Select Status"  %>
                    
      <div class="form-actions">
    <%= s.button :submit, class: 'btn btn-mini btn-success' %>
  </div>              
     
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
      <th>Trip Date</th>
      <th>Service Time</th>
      <th>Notes</th>
      <th>Location</th>
      <th>User ID</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.created_at.strftime("%b %d, %Y || %I:%M:%S:%p") %></td> 
        <td></td>
        <td><%= link_to 'Show', trip, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
   </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User ID:</strong>

  <%= @trip.user.id %>
</p>

<p>
  <strong>Trip ID:</strong>
   <%= @trip.id %>
  
</p>

<p>
  <strong>Statustime:</strong>
  
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

<hr> <hr>

<!-------------------------Status Form----------------------------------->

<%= simple_form_for([@trip, @trip.status_times.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     
    <%= f.input :status, collection: [ "On Duty Not Driving", "Driving", 
                    "Off Duty", "In Sleeper"], prompt: "Select Status"  %>
    <%= f.input :notes %>
    <%= f.input :location %>
   
    
   
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-mini btn-success' %>
  </div>
<% end %>

<!--------------------End Status Form----------------------------------->